# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wetlab', '0004_rundataparameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='BioInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info1', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=45)),
                ('userid', models.CharField(max_length=45)),
                ('libraryKit', models.CharField(max_length=45)),
                ('baseSpaceFile', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RawNextSeqStatisticsXml',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rawYield', models.CharField(max_length=64)),
                ('rawYieldQ30', models.CharField(max_length=64)),
                ('rawQuality', models.CharField(max_length=64)),
                ('PF_Yield', models.CharField(max_length=64)),
                ('PF_YieldQ30', models.CharField(max_length=64)),
                ('PF_Quality', models.CharField(max_length=64)),
                ('barcodeCount', models.CharField(max_length=64)),
                ('perfectBarcodeCount', models.CharField(max_length=64)),
                ('project', models.CharField(default='-', max_length=30)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wetlab.Document')),
            ],
        ),
        migrations.CreateModel(
            name='RunProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runName', models.CharField(max_length=45)),
                ('sampleSheet', models.FileField(upload_to='documents/')),
                ('generatedat', models.DateTimeField(auto_now_add=True)),
                ('runState', models.CharField(max_length=25)),
                ('generatedBSFile', models.BooleanField(default=False)),
                ('samples', models.CharField(max_length=45)),
                ('useSpaceImgMb', models.CharField(max_length=10)),
                ('useSpaceFastaMb', models.CharField(max_length=10)),
                ('useSpaceOtherMb', models.CharField(max_length=10)),
                ('requestedCenter', models.CharField(max_length=45)),
                ('bioinfo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wetlab.BioInfo')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=25)),
                ('userFirstName', models.CharField(max_length=45)),
                ('userLastName', models.CharField(max_length=45)),
                ('userArea', models.CharField(max_length=25)),
                ('userEmail', models.EmailField(max_length=45)),
            ],
        ),
        migrations.RemoveField(
            model_name='nextseqstatisticsxml',
            name='document',
        ),
        migrations.DeleteModel(
            name='NextSeqStatisticsXml',
        ),
        migrations.AddField(
            model_name='projects',
            name='runprocess_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wetlab.RunProcess'),
        ),
        migrations.AddField(
            model_name='projects',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wetlab.UserInfo'),
        ),
    ]
