# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wetlab', '0008_auto_20170729_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miseqstatisticsxml',
            name='document',
        ),
        migrations.RemoveField(
            model_name='rawnextseqstatisticsxml',
            name='document',
        ),
        migrations.RemoveField(
            model_name='rundataparameters',
            name='document',
        ),
        migrations.DeleteModel(
            name='MiSeqStatisticsXml',
        ),
        migrations.DeleteModel(
            name='RawNextSeqStatisticsXml',
        ),
        migrations.DeleteModel(
            name='RunDataParameters',
        ),
    ]
