version: '3.3'

services:
    db1:
        image: mysql:8.0
        container_name: db1
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: iskylims
            MYSQL_USER : django
            MYSQL_PASSWORD : djangopass
            MYSQL_ROOT_PASSWORD: root

        ports:
            - 6606:3306
        networks:
            - developv2
        volumes:
            - db1:/var/lib/mysql
            - /etc/localtime:/etc/localtime:ro
            - /usr/share/zoneinfo:/usr/share/zoneinfo

    web1:
        build: .
        container_name: iskylimsv2_app
        command: python3 /opt/iskylims/manage.py runserver 0:8001
        ports:
            - "8001:8004"
        networks:
            - developv2
        depends_on:
            - db1

        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /usr/share/zoneinfo:/usr/share/zoneinfo
networks:
  developv2:

volumes:
  db1:
