version: '3.8'

services:
  apache:
    container_name: iskylims_apache
    restart: unless-stopped
    image: registry.access.redhat.com/ubi9/httpd-24
    depends_on:
      - app
    ports:
      - "8080:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/zoneinfo:/usr/share/zoneinfo
      - ./conf/iskylims_apache_reverse_proxy.conf:/etc/httpd/conf.d/iskylims.conf:Z,ro
      - /var/log/local/apache:/var/log/httpd:Z

  app:
    container_name: iskylims_app
    restart: unless-stopped
    build:
      context: .
      args:
        INSTALL_TYPE: ${INSTALL_TYPE:-dep}
        GIT_REVISION: ${GIT_REVISION:-main}
        INSTALL_CONF: ${INSTALL_CONF:-conf/docker_production_settings.txt}
        APP_UID: ${APP_UID:-1212}
        APP_GID: ${APP_GID:-1212}
        APP_SHELL: ${APP_SHELL:-/sbin/nologin}
    expose:
      - "8001"
    environment:
      DJANGO_SETTINGS_MODULE: iskylims.settings
      APP_MODE: prod
    user: "${APP_UID:-1212}:${APP_GID:-1212}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/zoneinfo:/usr/share/zoneinfo
      - /var/log/local/apps/iskylims:/opt/iskylims/logs:Z
      - iskylims_documents:/opt/iskylims/documents
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  iskylims_documents:
