version: '3.4'

services:
    db:
        image: mysql:8.0
        container_name: db
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: iskylims_docker
            MYSQL_USER : django
            MYSQL_PASSWORD : djangopass
            MYSQL_ROOT_PASSWORD: root

        ports:
            - 6606:3306
        networks:
            - develop_net
        volumes:
            - db_data:/var/lib/mysql
            - /etc/localtime:/etc/localtime:ro
            - /usr/share/zoneinfo:/usr/share/zoneinfo
    
    samba:
        image: dperson/samba
        networks:
        - develop_net
        ports:
        - "137:137/udp"
        - "138:138/udp"
        - "139:139/tcp"
        - "445:445/tcp"
        read_only: true
        tmpfs:
        - /tmp
        restart: unless-stopped
        stdin_open: true
        tty: true
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /usr/share/zoneinfo:/usr/share/zoneinfo
            - ngs_data_vol:/mnt:z
        command: '-s "ngs_data;/mnt;yes;yes;no;samba_user;none;none;ngs data samba share" -u "samba_user;sambapasswd" -p'
    
    app:
        build: .
        container_name: iskylimsv2_app
        ports:
            - "8001:8001"
        networks:
            - develop_net
        depends_on:
            - db
            - samba
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /usr/share/zoneinfo:/usr/share/zoneinfo

networks:
  develop_net:

volumes:
  db_data:
  ngs_data_vol:
