version: '3.4'

services:
    db:
        image: mysql:8.0
        container_name: db
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        healthcheck:
          test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="djangopass" --silent']
          interval: 3s
          retries: 5
          start_period: 30s
        environment:
            MYSQL_DATABASE: iskylims_docker
            MYSQL_USER : django
            MYSQL_PASSWORD : djangopass
            MYSQL_ROOT_PASSWORD: root

        ports:
            - 6606:3306
        networks:
            - develop_net
        volumes:
            - db_data_vol:/var/lib/mysql
            - /etc/localtime:/etc/localtime:ro
            - /usr/share/zoneinfo:/usr/share/zoneinfo
    
    samba:
        image: dperson/samba
        container_name: samba
        networks:
        - develop_net
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /usr/share/zoneinfo:/usr/share/zoneinfo
            - ngs_data_vol:/mnt
        command: '-S -s "ngs_data;/mnt/test_ngs_data;yes;yes;no;samba_user;none;none;ngs data samba share" -u "samba_user;sambapasswd" -p'
    
    app:
        build: .
        container_name: iskylims_app
        ports:
            - "8001:8001"
        networks:
            - develop_net
        depends_on:
            db:
              condition: service_healthy
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /usr/share/zoneinfo:/usr/share/zoneinfo

networks:
  develop_net:

volumes:
  db_data_vol:
  ngs_data_vol: