# Generated by Django 4.2.25 on 2026-02-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moleculepreparation',
            old_name='molecule_used_for',
            new_name='sample_continues_on',
        ),
        migrations.RenameField(
            model_name='sampleprojectsfields',
            old_name='sample_project_searchable',
            new_name='sample_project_downloadable',
        ),
        migrations.AddField(
            model_name='city',
            name='geo_loc_city_cod',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='autonom_cod',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='center_class_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='dep_func',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='lab_code_1',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='lab_code_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='lab_function',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='lab_geo_loc_latitude',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='lab_geo_loc_longitude',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='post_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='protocolparameters',
            name='parameter_download',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='stateincountry',
            name='geo_loc_state_cod',
            field=models.CharField(blank=True, help_text='Geographic code of the CCAA', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='statesformolecule',
            name='molecule_state_display',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='labrequest',
            name='lab_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='moleculeusedfor',
            table='core_sample_continues_on',
        ),
    ]
