# ExtendedStatus controls whether Apache will generate "full" status
# information when the "server-status" handler is called.
ExtendedStatus On

<VirtualHost *:8080>
    ServerName ${SERVER_STATUS_SERVER_NAME}
    ServerAlias ${SERVER_STATUS_ALIASES}
    <Location /server-status>
        SetHandler server-status
        Order deny,allow
        Deny from all
        Allow from ${SERVER_STATUS_ALLOW_FROM}
    </Location>
</VirtualHost>
