# Generated by Django 4.2.25 on 2026-02-11 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drylab", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="service_status",
        ),
    ]
