# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availServiceDescription', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centerName', models.CharField(max_length=50)),
                ('centerAbbr', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryEstimatedDate', models.DateField()),
                ('deliveryNotes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FileExt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileExt', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platformName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolutionServiceSRV', models.CharField(max_length=10)),
                ('resolutionDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceName', models.CharField(max_length=50)),
                ('servicePosition', models.CharField(max_length=50)),
                ('serviceArea', models.CharField(max_length=50)),
                ('serviceExtension', models.CharField(max_length=5)),
                ('serviceEmail', models.EmailField(max_length=45)),
                ('serviceSeqCenter', models.CharField(max_length=50)),
                ('serviceRunSpecs', models.CharField(max_length=10)),
                ('serviceFile', models.FileField(upload_to='documents/')),
                ('serviceStatus', models.CharField(max_length=10)),
                ('serviceNotes', models.TextField(max_length=500)),
                ('serviceCenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drylab.Center')),
                ('serviceFileExt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drylab.FileExt')),
                ('servicePlatform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drylab.Platform')),
            ],
        ),
        migrations.AddField(
            model_name='resolution',
            name='resolutionServiceID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drylab.Service'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='deliveryResolutionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drylab.Resolution'),
        ),
        migrations.AddField(
            model_name='availableservice',
            name='availService',
            field=models.ManyToManyField(to='drylab.Service'),
        ),
        migrations.AddField(
            model_name='availableservice',
            name='availServiceParent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drylab.AvailableService'),
        ),
    ]
