# Generated by Django 2.0 on 2018-01-25 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centerName', models.CharField(max_length=50, verbose_name='Center')),
                ('centerAbbr', models.CharField(max_length=25, verbose_name='Center')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilePosition', models.CharField(max_length=50, verbose_name='Position')),
                ('profileArea', models.CharField(max_length=50, verbose_name='Area / Unit')),
                ('profileExtension', models.CharField(max_length=5, verbose_name='Phone extension')),
                ('profileCenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Center', verbose_name='Center')),
                ('profileUserID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
