# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 09:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centerName', models.CharField(max_length=50, verbose_name='Center')),
                ('centerAbbr', models.CharField(max_length=25, verbose_name='Center')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userInfoPosition', models.CharField(max_length=50, verbose_name='Position')),
                ('userInfoArea', models.CharField(max_length=50, verbose_name='Area / Unit')),
                ('userInfoExtension', models.CharField(max_length=5, verbose_name='Phone extension')),
                ('userInfoCenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Center', verbose_name='Center')),
                ('userInfoUserID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
