# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drylab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableservice',
            name='availServiceParent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drylab.AvailableService'),
        ),
    ]
