# Generated by Django 2.0 on 2018-03-08 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_auto_20180206_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileUserID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
