# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drylab', '0002_auto_20170807_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='deliveryDate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='deliveryNumber',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
