# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_center_userinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInfo',
            new_name='Profile',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='userInfoArea',
            new_name='profileArea',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='userInfoCenter',
            new_name='profileCenter',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='userInfoExtension',
            new_name='profileExtension',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='userInfoPosition',
            new_name='profilePosition',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='userInfoUserID',
            new_name='profileUserID',
        ),
    ]
