# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drylab', '0003_auto_20170807_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availableservice',
            name='availService',
        ),
        migrations.AddField(
            model_name='service',
            name='serviceAvailableService',
            field=models.ManyToManyField(to='drylab.AvailableService'),
        ),
    ]
