# Generated by Django 3.2 on 2023-04-29 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("django_utils", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="center",
            old_name="centerAbbr",
            new_name="center_abbr",
        ),
        migrations.RenameField(
            model_name="center",
            old_name="centerName",
            new_name="center_name",
        ),
        migrations.RenameField(
            model_name="classificationarea",
            old_name="classificationAreaDescription",
            new_name="classification_area_description",
        ),
        migrations.RenameField(
            model_name="classificationarea",
            old_name="classificationAreaName",
            new_name="classification_area_name",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="profileArea",
            new_name="profile_area",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="profileCenter",
            new_name="profile_center",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="profileClassificationArea",
            new_name="profile_classification_area",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="profileExtension",
            new_name="profile_extension",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="profilePosition",
            new_name="profile_position",
        ),
        migrations.RenameField(
            model_name="profile", old_name="profileUserID", new_name="profile_user_id"
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_user_id",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to="auth.user",
            ),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name="center",
            table="utils_center",
        ),
        migrations.AlterModelTable(
            name="classificationarea",
            table="utils_classification_area",
        ),
        migrations.AlterModelTable(
            name="profile",
            table="utils_profile",
        ),
    ]
