# Generated by Django 4.2.25 on 2026-02-11 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicSampleRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entry_order", models.CharField(blank=True, max_length=8, null=True)),
                (
                    "confirmation_code",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("priority", models.IntegerField(blank=True, null=True)),
                ("comments", models.CharField(blank=True, max_length=255, null=True)),
                ("service_date", models.DateTimeField(blank=True, null=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ClinicSampleState",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clinic_state", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="ConfigSetting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("configuration_name", models.CharField(max_length=80)),
                (
                    "configuration_value",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="FamilyRelatives",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("relationship", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="PatientData",
            fields=[
                (
                    "patien_core",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="core.patientcore",
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.CharField(blank=True, max_length=50, null=True)),
                ("birthday", models.DateTimeField(blank=True, null=True)),
                ("smoker", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "notification_preference",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("comments", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ServiceUnits",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_unit_name", models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name="ResultParameterValue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parameterValue", models.CharField(max_length=255)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "clinicSample_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinic.clinicsamplerequest",
                    ),
                ),
                (
                    "parameter_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.protocolparameters",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatientHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entry_date", models.DateTimeField(blank=True, null=True)),
                ("description", models.CharField(max_length=255)),
                (
                    "patient_core",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.patientcore",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Family",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("family_id", models.CharField(max_length=50)),
                ("relative_1", models.CharField(max_length=50)),
                ("relative_2", models.CharField(max_length=50)),
                ("affected", models.BooleanField()),
                (
                    "family_comments",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "family_relatives_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinic.familyrelatives",
                    ),
                ),
                (
                    "patien_core_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.patientcore",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doctor_name", models.CharField(max_length=80)),
                (
                    "service_unit_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinic.serviceunits",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="clinicsamplerequest",
            name="clinic_sample_state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="clinic.clinicsamplestate",
            ),
        ),
        migrations.AddField(
            model_name="clinicsamplerequest",
            name="doctor_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="clinic.doctor",
            ),
        ),
        migrations.AddField(
            model_name="clinicsamplerequest",
            name="patient_core",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.patientcore",
            ),
        ),
        migrations.AddField(
            model_name="clinicsamplerequest",
            name="sample_core",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.samples"
            ),
        ),
        migrations.AddField(
            model_name="clinicsamplerequest",
            name="sample_request_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="clinicsamplerequest",
            name="service_unit_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="clinic.serviceunits",
            ),
        ),
    ]
