# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_name', models.CharField(blank=True, max_length=255)),
                ('project_name', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('csv_file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('user_id', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('convert', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BaseSpaceFile',
            fields=[
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='polls.Document')),
                ('baseSpace_file', models.CharField(max_length=255)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
