# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wetlab', '0006_auto_20170727_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='userid',
        ),
        migrations.AddField(
            model_name='projects',
            name='procState',
            field=models.CharField(default='', max_length=25),
        ),
    ]
