# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextSeqStatisticsBin',
            fields=[
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='polls.Document')),
                ('lane', models.CharField(max_length=10)),
                ('singleRead', models.CharField(max_length=10)),
                ('tiles', models.CharField(max_length=10)),
                ('density', models.CharField(max_length=10)),
                ('cluster_PF', models.CharField(max_length=10)),
                ('phas_prephas', models.CharField(max_length=10)),
                ('reads', models.CharField(max_length=10)),
                ('reads_PF', models.CharField(max_length=10)),
                ('q30', models.CharField(max_length=10)),
                ('yields', models.CharField(max_length=10)),
                ('cyclesErrRated', models.CharField(max_length=10)),
                ('aligned', models.CharField(max_length=10)),
                ('errorRate', models.CharField(max_length=10)),
                ('errorRate35', models.CharField(max_length=10)),
                ('errorRate75', models.CharField(max_length=10)),
                ('errorRate100', models.CharField(max_length=10)),
                ('intensityCycle', models.CharField(max_length=10)),
                ('comments', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
