# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 22:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_nextseqstatisticsbin'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiSeqStatisticsXml',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rawYield', models.CharField(max_length=20)),
                ('rawYieldQ30', models.CharField(max_length=20)),
                ('rawQuality', models.CharField(max_length=20)),
                ('PF_Yield', models.CharField(max_length=20)),
                ('PF_YieldQ30', models.CharField(max_length=20)),
                ('PF_Quality', models.CharField(max_length=20)),
                ('barcodeCount', models.CharField(max_length=20)),
                ('perfectBarcodeCount', models.CharField(max_length=20)),
                ('project', models.CharField(default=False, max_length=30)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Document')),
            ],
        ),
        migrations.CreateModel(
            name='NextSeqStatisticsXml',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rawYield', models.CharField(max_length=20)),
                ('rawYieldQ30', models.CharField(max_length=20)),
                ('rawQuality', models.CharField(max_length=20)),
                ('PF_Yield', models.CharField(max_length=20)),
                ('PF_YieldQ30', models.CharField(max_length=20)),
                ('PF_Quality', models.CharField(max_length=20)),
                ('barcodeCount', models.CharField(max_length=20)),
                ('perfectBarcodeCount', models.CharField(max_length=20)),
                ('project', models.CharField(default=False, max_length=30)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Document')),
            ],
        ),
        migrations.RemoveField(
            model_name='nextseqstatisticsbin',
            name='document',
        ),
        migrations.DeleteModel(
            name='NextSeqStatisticsBin',
        ),
    ]
