# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20170718_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunDataParameters',
            fields=[
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='polls.Document')),
                ('RunID', models.CharField(max_length=255)),
                ('ExperimentName', models.CharField(max_length=255)),
                ('RTAVersion', models.CharField(max_length=255)),
                ('SystemSuiteVersion', models.CharField(max_length=255)),
                ('LibraryID', models.CharField(max_length=255)),
                ('Chemistry', models.CharField(max_length=255)),
                ('RunStartDate', models.CharField(max_length=255)),
                ('AnalysisWorkflowType', models.CharField(max_length=255)),
                ('RunManagementType', models.CharField(max_length=255)),
                ('PlannedRead1Cycles', models.CharField(max_length=255)),
                ('PlannedRead2Cycles', models.CharField(max_length=255)),
                ('PlannedIndex1ReadCycles', models.CharField(max_length=255)),
                ('PlannedIndex2ReadCycles', models.CharField(max_length=255)),
                ('ApplicationVersion', models.CharField(max_length=255)),
                ('NumTilesPerSwath', models.CharField(max_length=255)),
                ('ImageChannel', models.CharField(max_length=255)),
                ('Flowcell', models.CharField(max_length=255)),
                ('ImageDimensions', models.CharField(max_length=255)),
                ('FlowcellLayout', models.CharField(max_length=255)),
            ],
        ),
    ]
