# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20170729_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='procState',
            field=models.CharField(default='Not Started', max_length=25),
        ),
    ]
