# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BioInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info1', models.CharField(max_length=45)),
                ('info2', models.CharField(default='', max_length=45)),
                ('serviceRegistration', models.CharField(default='not required', max_length=45)),
                ('researcher', models.CharField(default='', max_length=45)),
                ('department', models.CharField(default='not assigned', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_name', models.CharField(blank=True, max_length=255)),
                ('project_name', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('csv_file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('user_id', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('convert', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=45)),
                ('procState', models.CharField(default='Not Started', max_length=25)),
                ('libraryKit', models.CharField(max_length=45)),
                ('baseSpaceFile', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RunProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runName', models.CharField(max_length=45)),
                ('sampleSheet', models.FileField(upload_to='documents/')),
                ('generatedat', models.DateTimeField(auto_now_add=True)),
                ('runState', models.CharField(max_length=25)),
                ('generatedBSFile', models.BooleanField(default=False)),
                ('samples', models.CharField(max_length=45)),
                ('useSpaceImgMb', models.CharField(max_length=10)),
                ('useSpaceFastaMb', models.CharField(max_length=10)),
                ('useSpaceOtherMb', models.CharField(max_length=10)),
                ('requestedCenter', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=25)),
                ('userFirstName', models.CharField(max_length=45)),
                ('userLastName', models.CharField(max_length=45)),
                ('userArea', models.CharField(max_length=25)),
                ('userEmail', models.EmailField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='BaseSpaceFile',
            fields=[
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wetlab.Document')),
                ('baseSpace_file', models.CharField(max_length=255)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RunningParameters',
            fields=[
                ('runName_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wetlab.RunProcess')),
                ('RunID', models.CharField(max_length=255)),
                ('ExperimentName', models.CharField(max_length=255)),
                ('RTAVersion', models.CharField(max_length=255)),
                ('SystemSuiteVersion', models.CharField(max_length=255)),
                ('LibraryID', models.CharField(max_length=255)),
                ('Chemistry', models.CharField(max_length=255)),
                ('RunStartDate', models.CharField(max_length=255)),
                ('AnalysisWorkflowType', models.CharField(max_length=255)),
                ('RunManagementType', models.CharField(max_length=255)),
                ('PlannedRead1Cycles', models.CharField(max_length=255)),
                ('PlannedRead2Cycles', models.CharField(max_length=255)),
                ('PlannedIndex1ReadCycles', models.CharField(max_length=255)),
                ('PlannedIndex2ReadCycles', models.CharField(max_length=255)),
                ('ApplicationVersion', models.CharField(max_length=255)),
                ('NumTilesPerSwath', models.CharField(max_length=255)),
                ('ImageChannel', models.CharField(max_length=255)),
                ('Flowcell', models.CharField(max_length=255)),
                ('ImageDimensions', models.CharField(max_length=255)),
                ('FlowcellLayout', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='runprocess',
            name='bioinfo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wetlab.BioInfo'),
        ),
        migrations.AddField(
            model_name='projects',
            name='runprocess_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wetlab.RunProcess'),
        ),
        migrations.AddField(
            model_name='projects',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wetlab.UserInfo'),
        ),
    ]
