## Module containing checks performed on a SampleSheet file for Illumina sequencers
from  iSkyLIMS_wetlab.models import *
import os
import pdb

from django.conf import settings
from .sample_convertion import get_projects_in_run

def check_run_name_free_to_use(run_name):
    ## Function checks whether run_name is already used in the database.
    ## Error page is shown if run_name is already  defined
    ##

    import pdb; pdb.set_trace()
    run_name_free_result='KO in check_run_name_free_to_use()'
    if (RunProcess.objects.filter(runName = run_name)).exists():
        if RunProcess.objects.filter(runName = run_name, runState__exact ='Pre-Recorded'):
            ## Delete the sample sheet file and the row in database
            delete_run = RunProcess.objects.filter(runName = run_name, runState__exact ='Pre-Recorded')
            sample_sheet_file = str(delete_run[0].sampleSheet)
            full_path_sample_sheet_file = os.path.join(settings.MEDIA_ROOT, sample_sheet_file)
            os.remove(full_path_sample_sheet_file)
            delete_run[0].delete()
            run_name_free_result='Free'
        else:#runState != 'Pre-Recorded'
            run_name_free_result=['Run Name is already used. ',
                                  'Run Name must be unique in database.', ' ',
                                  'ADVICE:',
                                  'Change the value in the Sample Sheet  file ']
    else: # run_name is new
        run_name_free_result='Free'
    return run_name_free_result



def check_run_projects_in_samplesheet(samplesheet):
    ## Check that there are projects declared within the run
    project_list=get_projects_in_run(samplesheet)
    message_output='KO in check_run_projects_in_samplesheet'

    import pdb; pdb.set_trace()
    if len (project_list) == 0 :
        message_output=[
            'Sample Sheet does not contain "Sample project" and/or "Description" fields',
            '', 'ADVICE:',
            'Check that csv file generated by Illumina Experient Manager'
            ' (IEM) includes these columns']
    else:
        message_output='OK_projects_samplesheet'
    return message_output



def check_run_users_definition(samplesheet):
    ## CHECK if the users are already defined in database.
    message_output='KO in check_run_users_definition'
    user_not_defined=[]
    project_list=get_projects_in_run(samplesheet)

    import pdb; pdb.set_trace()
    for key, val  in project_list.items():
        if ( not User.objects.filter(username__icontains = val).exists()):
            user_not_defined.append(val)
    import pdb; pdb.set_trace()
    if (len(user_not_defined)>0):
        if (len(user_not_defined)>1):
            head_text='The following users are not defined in database:'
        else:
            head_text='The following user is not defined in database:'
        ## convert the list into string to display the user names on error page
        display_user= ' ,  '.join(user_not_defined)
        message_output=[head_text,'', display_user,'',
            'Researcher names must be installed in database before uploading the Sample sheet']
    else:
        message_output='OK_users'
    return message_output



def check_run_projects_definition(project_list):
    ## Check that the projects are already defined in the database
    message_output='KO in check_run_projects_definition'
    project_already_defined=[]
    import pdb; pdb.set_trace()
    for key, val  in project_list.items():
        # check if project was already saved in database in Not Started State.
        # if found delete the projects, because the previous attempt to complete the run was unsuccessful
        if ( Projects.objects.filter(projectName__icontains = key).exists()):
            if ( Projects.objects.filter(projectName__icontains = key, procState__exact = 'Not Started').exists()):
                delete_project = Projects.objects.filter(projectName__icontains = key , procState__exact = 'Not Started')
                delete_project[0].delete()
            else:
                project_already_defined.append(key)
    import pdb; pdb.set_trace()
    if (len(project_already_defined)>0):
        if (len(project_already_defined)>1):
            head_text='The following projects are already defined in database:'
        else:
            head_text='The following project is already defined in database:'
        ## convert the list into string to display the user names on error page
        display_project= '  '.join(project_already_defined)
        message_output= [ head_text,'', display_project,'',
                        'Project names must be unique', '', 'ADVICE:',
                        'Edit the Sample Sheet file to correct this error']
    else:
        message_output="OK_projects_db"
    return message_output
