# Generated by Django 4.2.25 on 2026-02-11 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
        ("django_utils", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionaKitsLibPrepare",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kit_name", models.CharField(max_length=255)),
                (
                    "description",
                    models.CharField(blank=True, max_length=400, null=True),
                ),
                ("kit_order", models.IntegerField()),
                ("kit_used", models.BooleanField()),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "commercial_kit_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.commercialkits",
                    ),
                ),
                (
                    "protocol_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.protocols"
                    ),
                ),
                (
                    "register_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "wetlab_lib_additional_kits_lib_prepare",
            },
        ),
        migrations.CreateModel(
            name="CollectionIndexKit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collection_index_name", models.CharField(max_length=125)),
                ("version", models.CharField(max_length=80, null=True)),
                ("plate_extension", models.CharField(max_length=125, null=True)),
                ("adapter_1", models.CharField(max_length=125, null=True)),
                ("adapter_2", models.CharField(max_length=125, null=True)),
                (
                    "collection_index_file",
                    models.FileField(
                        max_length=500, upload_to="wetlab/collection_index_kits/"
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "db_table": "wetlab_collection_index_kit",
            },
        ),
        migrations.CreateModel(
            name="ConfigSetting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("configuration_name", models.CharField(max_length=80)),
                (
                    "configuration_value",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "wetlab_config_setting",
            },
        ),
        migrations.CreateModel(
            name="LibPrepareStates",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lib_prep_state", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "wetlab_lib_prepare_states",
            },
        ),
        migrations.CreateModel(
            name="LibraryKit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("library_name", models.CharField(max_length=125)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "wetlab_library_kit",
            },
        ),
        migrations.CreateModel(
            name="PoolStates",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pool_state", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "wetlab_pool_states",
            },
        ),
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_space_library",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
                ("project_name", models.CharField(max_length=45)),
                (
                    "library_kit",
                    models.CharField(blank=True, max_length=125, null=True),
                ),
                (
                    "base_space_file",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("project_run_date", models.DateField(blank=True, null=True)),
                (
                    "library_kit_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wetlab.librarykit",
                    ),
                ),
            ],
            options={
                "db_table": "wetlab_projects",
            },
        ),
        migrations.CreateModel(
            name="RunConfigurationTest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_test_name", models.CharField(max_length=80)),
                ("run_test_folder", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "wetlab_lib_run_configuration_test",
            },
        ),
        migrations.CreateModel(
            name="RunErrors",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("error_code", models.CharField(max_length=10)),
                ("error_text", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "wetlab_run_errors",
            },
        ),
        migrations.CreateModel(
            name="RunProcess",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_name", models.CharField(max_length=45)),
                (
                    "sample_sheet",
                    models.FileField(
                        blank=True, null=True, upload_to="wetlab/sample_sheet/"
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("run_date", models.DateField(blank=True, null=True)),
                ("run_finish_date", models.DateTimeField(blank=True, null=True)),
                ("bcl2fastq_finish_date", models.DateTimeField(blank=True, null=True)),
                ("run_completed_date", models.DateTimeField(blank=True, null=True)),
                (
                    "run_forced_continue_on_error",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "index_library",
                    models.CharField(blank=True, max_length=85, null=True),
                ),
                ("samples", models.CharField(blank=True, max_length=45)),
                ("use_space_img_mb", models.CharField(blank=True, max_length=10)),
                ("use_space_fasta_mb", models.CharField(blank=True, max_length=10)),
                ("use_space_other_mb", models.CharField(blank=True, max_length=10)),
                (
                    "center_requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_utils.center",
                    ),
                ),
                (
                    "reagent_kit",
                    models.ManyToManyField(blank=True, to="core.userlotcommercialkits"),
                ),
                (
                    "run_error",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wetlab.runerrors",
                    ),
                ),
            ],
            options={
                "db_table": "wetlab_run_process",
            },
        ),
        migrations.CreateModel(
            name="RunStates",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_state_name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "wetlab_run_states",
            },
        ),
        migrations.CreateModel(
            name="SambaConnectionData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "samba_folder_name",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("domain", models.CharField(blank=True, max_length=80, null=True)),
                ("host_name", models.CharField(blank=True, max_length=80, null=True)),
                ("ip_server", models.CharField(blank=True, max_length=20, null=True)),
                ("port_server", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "remote_server_name",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "shared_folder_name",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("user_id", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "user_password",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("is_direct_tcp", models.BooleanField(default=True)),
                ("ntlm_used", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "wetlab_samba_connection_data",
            },
        ),
        migrations.CreateModel(
            name="RunningParameters",
            fields=[
                (
                    "run_name_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="wetlab.runprocess",
                    ),
                ),
                ("run_id", models.CharField(max_length=255)),
                ("experiment_name", models.CharField(max_length=255)),
                (
                    "rta_version",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "system_suite_version",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("library_id", models.CharField(blank=True, max_length=255, null=True)),
                ("chemistry", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "run_start_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "analysis_workflow_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "run_management_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "planned_read1_cycles",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "planned_read2_cycles",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "planned_index1_read_cycles",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "planned_index2_read_cycles",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "application_version",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "num_tiles_per_swath",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "image_channel",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("flowcell", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "image_dimensions",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "flowcell_layout",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "wetlab_running_parameters",
            },
        ),
        migrations.CreateModel(
            name="StatsRunSummary",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.CharField(max_length=20)),
                ("yield_total", models.CharField(max_length=10)),
                ("projected_total_yield", models.CharField(max_length=10)),
                ("aligned", models.CharField(max_length=10)),
                ("error_rate", models.CharField(max_length=10)),
                ("intensity_cycle", models.CharField(max_length=10)),
                ("bigger_q30", models.CharField(max_length=10)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("stats_summary_run_date", models.DateField(null=True)),
                (
                    "runprocess_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wetlab.runprocess",
                    ),
                ),
            ],
            options={
                "db_table": "wetlab_stats_run_summary",
            },
        ),
        migrations.CreateModel(
            name="StatsRunRead",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("read", models.CharField(max_length=10)),
                ("lane", models.CharField(max_length=10)),
                ("tiles", models.CharField(max_length=10)),
                ("density", models.CharField(max_length=40)),
                ("cluster_pf", models.CharField(max_length=40)),
                ("phas_prephas", models.CharField(max_length=40)),
                ("reads", models.CharField(max_length=40)),
                ("reads_pf", models.CharField(max_length=40)),
                ("q30", models.CharField(max_length=40)),
                ("yields", models.CharField(max_length=40)),
                ("cycles_err_rated", models.CharField(max_length=40)),
                ("aligned", models.CharField(max_length=40)),
                ("error_rate", models.CharField(max_length=40)),
                ("error_rate_35", models.CharField(max_length=40)),
                ("error_rate_50", models.CharField(max_length=40)),
                ("error_rate_75", models.CharField(max_length=40)),
                ("error_rate_100", models.CharField(max_length=40)),
                ("intensity_cycle", models.CharField(max_length=40)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("stats_read_run_date", models.DateField(null=True)),
                (
                    "runprocess_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wetlab.runprocess",
                    ),
                ),
            ],
            options={
                "db_table": "wetlab_stats_run_read",
            },
        ),
        migrations.CreateModel(
            name="StatsLaneSummary",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("default_all", models.CharField(max_length=40, null=True)),
                ("lane", models.CharField(max_length=10)),
                ("pf_cluster", models.CharField(max_length=64)),
                ("percent_lane", models.CharField(max_length=64)),
                ("perfect_barcode", models.CharField(max_length=64)),
                ("one_mismatch", models.CharField(max_length=64)),
                ("yield_mb", models.CharField(max_length=64)),
                ("bigger_q30", models.CharField(max_length=64)),
                ("mean_quality", models.CharField(max_length=64)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wetlab.projects",
                    ),
                ),
                (
                    "runprocess_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wetlab.runprocess",
                    ),
                ),
            ],
            options={
                "db_table": "wetlab_stats_lane_summary",
            },
        ),
        migrations.CreateModel(
            name="StatsFlSummary",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("default_all", models.CharField(max_length=40, null=True)),
                ("flow_raw_cluster", models.CharField(max_length=40)),
                ("flow_pf_cluster", models.CharField(max_length=40)),
                ("flow_yield_mb", models.CharField(max_length=40)),
                ("sample_number", models.CharField(max_length=40)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wetlab.projects",
                    ),
                ),
                (
                    "runprocess_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wetlab.runprocess",
                    ),
                ),
            ],
            options={
                "db_table": "wetlab_stats_fl_summary",
            },
        ),
        migrations.CreateModel(
            name="SamplesInProject",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sample_name", models.CharField(max_length=255)),
                ("barcode_name", models.CharField(max_length=255)),
                ("pf_clusters", models.CharField(max_length=55)),
                ("percent_in_project", models.CharField(max_length=25)),
                ("yield_mb", models.CharField(max_length=55)),
                ("quality_q30", models.CharField(max_length=55)),
                ("mean_quality", models.CharField(max_length=55)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wetlab.projects",
                    ),
                ),
                (
                    "run_process_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wetlab.runprocess",
                    ),
                ),
                (
                    "sample_in_core",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.samples",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "wetlab_samples_in_project",
            },
        ),
        migrations.AddField(
            model_name="runprocess",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="state_of_run",
                to="wetlab.runstates",
            ),
        ),
        migrations.AddField(
            model_name="runprocess",
            name="state_before_error",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="wetlab.runstates",
            ),
        ),
        migrations.AddField(
            model_name="runprocess",
            name="used_sequencer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.sequencerinlab",
            ),
        ),
        migrations.CreateModel(
            name="RawTopUnknowBarcodes",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lane_number", models.CharField(max_length=4)),
                ("top_number", models.CharField(max_length=4)),
                ("count", models.CharField(max_length=40)),
                ("sequence", models.CharField(max_length=40)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "runprocess_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wetlab.runprocess",
                    ),
                ),
            ],
            options={
                "db_table": "wetlab_raw_top_unknown_barcodes",
            },
        ),
        migrations.CreateModel(
            name="RawDemuxStats",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("default_all", models.CharField(max_length=40, null=True)),
                ("raw_yield", models.CharField(max_length=255)),
                ("raw_yield_q30", models.CharField(max_length=255)),
                ("raw_quality", models.CharField(max_length=255)),
                ("pf_yield", models.CharField(max_length=255)),
                ("pf_yield_q30", models.CharField(max_length=255)),
                ("pf_quality_score", models.CharField(max_length=255)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wetlab.projects",
                    ),
                ),
                (
                    "runprocess_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wetlab.runprocess",
                    ),
                ),
            ],
            options={
                "db_table": "wetlab_raw_demux_stats",
            },
        ),
        migrations.AddField(
            model_name="projects",
            name="run_process",
            field=models.ManyToManyField(to="wetlab.runprocess"),
        ),
        migrations.AddField(
            model_name="projects",
            name="user_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="LibUserSampleSheet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sample_sheet",
                    models.FileField(upload_to="wetlab/sample_sheets_lib_prep/"),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("application", models.CharField(blank=True, max_length=70, null=True)),
                ("instrument", models.CharField(blank=True, max_length=70, null=True)),
                ("adapter_1", models.CharField(blank=True, max_length=70, null=True)),
                ("adapter_2", models.CharField(blank=True, max_length=70, null=True)),
                ("assay", models.CharField(blank=True, max_length=70, null=True)),
                ("reads", models.CharField(blank=True, max_length=10, null=True)),
                ("confirmed_used", models.BooleanField(default=False)),
                ("iem_version", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "collection_index_kit_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wetlab.collectionindexkit",
                    ),
                ),
                (
                    "register_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sequencing_configuration",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.sequencingconfiguration",
                    ),
                ),
            ],
            options={
                "db_table": "wetlab_lib_user_samplesheet",
            },
        ),
        migrations.CreateModel(
            name="LibraryPool",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pool_name", models.CharField(max_length=50)),
                ("sample_number", models.IntegerField(default=0)),
                ("pool_code_id", models.CharField(blank=True, max_length=50)),
                ("adapter", models.CharField(blank=True, max_length=50, null=True)),
                ("paired_end", models.CharField(blank=True, max_length=10, null=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "platform",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.sequencingplatform",
                    ),
                ),
                (
                    "pool_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wetlab.poolstates",
                    ),
                ),
                (
                    "register_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "run_process_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wetlab.runprocess",
                    ),
                ),
            ],
            options={
                "db_table": "wetlab_library_pool",
                "ordering": ("pool_name",),
            },
        ),
        migrations.CreateModel(
            name="LibPrepare",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lib_prep_code_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "user_sample_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "project_in_samplesheet",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "sample_plate",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("sample_well", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "index_plate_well",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("i7_index_id", models.CharField(blank=True, max_length=25, null=True)),
                ("i7_index", models.CharField(blank=True, max_length=30, null=True)),
                ("i5_index_id", models.CharField(blank=True, max_length=25, null=True)),
                ("i5_index", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "genome_folder",
                    models.CharField(blank=True, max_length=180, null=True),
                ),
                ("manifest", models.CharField(blank=True, max_length=80, null=True)),
                ("reused_number", models.IntegerField(default=0)),
                ("unique_id", models.CharField(blank=True, max_length=16, null=True)),
                (
                    "user_in_samplesheet",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "samplename_in_samplesheet",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "prefix_protocol",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                (
                    "lib_prep_state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wetlab.libpreparestates",
                    ),
                ),
                (
                    "molecule_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.moleculepreparation",
                    ),
                ),
                ("pools", models.ManyToManyField(blank=True, to="wetlab.librarypool")),
                (
                    "protocol_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.protocols",
                    ),
                ),
                (
                    "register_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sample_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.samples",
                    ),
                ),
                (
                    "user_lot_kit_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.userlotcommercialkits",
                    ),
                ),
                (
                    "user_sample_sheet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wetlab.libusersamplesheet",
                    ),
                ),
            ],
            options={
                "db_table": "wetlab_lib_prepare",
                "ordering": ("lib_prep_code_id",),
            },
        ),
        migrations.CreateModel(
            name="LibParameterValue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parameter_value", models.CharField(max_length=255)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "library_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wetlab.libprepare",
                    ),
                ),
                (
                    "parameter_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.protocolparameters",
                    ),
                ),
            ],
            options={
                "db_table": "wetlab_lib_parameter_value",
            },
        ),
        migrations.CreateModel(
            name="GraphicsStats",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("folder_run_graphic", models.CharField(max_length=255)),
                ("cluster_count_graph", models.CharField(max_length=255)),
                ("flowcell_graph", models.CharField(max_length=255)),
                ("intensity_by_cycle_graph", models.CharField(max_length=255)),
                ("heatmap_graph", models.CharField(max_length=255)),
                ("histogram_graph", models.CharField(max_length=255)),
                ("sample_qc_graph", models.CharField(max_length=255)),
                ("generated_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "runprocess_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wetlab.runprocess",
                    ),
                ),
            ],
            options={
                "db_table": "wetlab_graphics_stats",
            },
        ),
        migrations.CreateModel(
            name="CollectionIndexValues",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("default_well", models.CharField(max_length=10, null=True)),
                ("index_7", models.CharField(max_length=25, null=True)),
                ("i_7_seq", models.CharField(max_length=25, null=True)),
                ("index_5", models.CharField(max_length=25, null=True)),
                ("i_5_seq", models.CharField(max_length=25, null=True)),
                (
                    "collection_index_kit_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wetlab.collectionindexkit",
                    ),
                ),
            ],
            options={
                "db_table": "wetlab_collection_index_values",
            },
        ),
        migrations.CreateModel(
            name="AdditionalUserLotKit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=255)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "additional_lot_kits",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wetlab.additionakitslibprepare",
                    ),
                ),
                (
                    "lib_prep_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wetlab.libprepare",
                    ),
                ),
                (
                    "user_lot_kit_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.userlotcommercialkits",
                    ),
                ),
            ],
            options={
                "db_table": "wetlab_lib_additional_user_lot_kit",
            },
        ),
    ]
