# Generated by Django 4.2.25 on 2026-02-11 16:33

from django.db import migrations, models


def drop_librarypool_run_process_id(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT 1
            FROM information_schema.COLUMNS
            WHERE TABLE_SCHEMA = DATABASE()
              AND TABLE_NAME = 'wetlab_library_pool'
              AND COLUMN_NAME = 'run_process_id_id'
            """)
        if cursor.fetchone() is None:
            return

        cursor.execute("""
            SELECT CONSTRAINT_NAME
            FROM information_schema.KEY_COLUMN_USAGE
            WHERE TABLE_SCHEMA = DATABASE()
              AND TABLE_NAME = 'wetlab_library_pool'
              AND COLUMN_NAME = 'run_process_id_id'
              AND REFERENCED_TABLE_NAME IS NOT NULL
            """)
        for (constraint_name,) in cursor.fetchall():
            cursor.execute(
                f"ALTER TABLE wetlab_library_pool DROP FOREIGN KEY `{constraint_name}`"
            )

        cursor.execute("ALTER TABLE wetlab_library_pool DROP COLUMN run_process_id_id")


class Migration(migrations.Migration):

    dependencies = [
        ("wetlab", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            """
            UPDATE wetlab_raw_top_unknown_barcodes
            SET count = NULL
            WHERE count IS NOT NULL AND count NOT REGEXP '^[0-9]+$'
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    drop_librarypool_run_process_id, migrations.RunPython.noop
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name="librarypool",
                    name="run_process_id",
                ),
            ],
        ),
        migrations.AddField(
            model_name="runprocess",
            name="library_pool",
            field=models.ManyToManyField(blank=True, to="wetlab.librarypool"),
        ),
        migrations.AddField(
            model_name="runstates",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="runstates",
            name="show_in_stats",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="runstates",
            name="state_display",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name="libprepare",
            name="prefix_protocol",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="rawtopunknowbarcodes",
            name="count",
            field=models.IntegerField(),
        ),
    ]
