name: Close Issues on Develop Merge

on:
  pull_request:
    types:
      - closed

jobs:
  close-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Close linked issues
        uses: peter-evans/close-issue@v2
        with:
          comment: "This issue is automatically closed as the fix has been merged into `develop`."
